/*!

 \brief Class which implements messages for rollback

 RollbackMessage.h

 Author: Michael Lees (mhl)
 Date: 10/02/2005

 Description: The is the class that implements the rollback message. It
 has a rollback Tag to identify the origin of a rollback (used to
 prevent the same LP from rolling back twice as a result of the same
 straggler). Rollback messages are generated by Clps, whereas
 anti-messages are generated by Alps.


 Revisions:

 */
//This has been moved to simulation messages as it doesn't have a
//solid reason for being in the Control messages (ie., strictly
//there is no reason for not blocking rollback messages?). However
//it does need to be considered in GVT calculations. Which perhaps
//is a better distinction for Control messages and simulation
//messages.
#ifndef ROLLBACKMESSAGE_H_
#define ROLLBACKMESSAGE_H_

#include "SimulationMessage.h"
#include "HasRollbackTag.h"
#include "HasOriginalAgent.h"

namespace pdesmas {
  class RollbackMessage: public SimulationMessage, public HasRollbackTag, public HasOriginalAgent {
    private:
      static AbstractMessage* CreateInstance();

    public:
      RollbackMessage();
      virtual ~RollbackMessage();

      pdesmasType GetType() const;

      void Serialise(ostream&) const;
      void Deserialise(istream&);
  };
}
#endif
